version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build: ./backend
    container_name: backend
    env_file: .env

    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    restart: always
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &&
                    python3 manage.py runserver 0.0.0.0:8000"



  node:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/front

      
volumes:
  postgres_data:


